// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
	    int N = Integer.parseInt(args[0]);
		int higher = 0 , smaller = 0 ;                         // veriables for higher or smaller (equal) then 0.5
		double Ratio;

		for (int i = 0 ; i < N ; i++ ) {
			double Random = Math.random();
			if (Random > 0.5) {
				higher++;
			} else {
				smaller++;
			}
		}

		if ( higher > smaller ) {
			Ratio = (double) smaller / higher ;
		} else {
			Ratio = (double) higher / smaller ;
		}


		if ((higher == 0) || (smaller == 0)) {
			System.out.println("> 0.5: " + higher);
			System.out.println("<<= 0.5: " + smaller);
		} else {
			System.out.println("> 0.5: " + higher);
			System.out.println("<<= 0.5: " + smaller);
			System.out.println("Ratio: " + Ratio);
		}
		
	}
}
